module.exports = {
  User: require('./User'),
  Topic: require('./Topic'),
  PlatformIntegration: require('./PlatformIntegration'),
  Problem: require('./Problem'),
  Submission: require('./Submission'),
  Roadmap: require('./Roadmap'),
  RoadmapTopic: require('./RoadmapTopic'),
  RoadmapTopicProblem: require('./RoadmapTopicProblem'),
  UserRoadmapProgress: require('./UserRoadmapProgress'),
  MasteryMetric: require('./MasteryMetric'),
  WeakTopicSignal: require('./WeakTopicSignal'),
  PreparationTask: require('./PreparationTask'),
  RevisionSchedule: require('./RevisionSchedule'),
  ReadinessScore: require('./ReadinessScore'),
  PracticeSession: require('./PracticeSession'),
  AIMentorConversation: require('./AIMentorConversation'),
  AnalyticsSnapshot: require('./AnalyticsSnapshot'),
  CanonicalProblem: require('./CanonicalProblem'),
  PlatformProblemMapping: require('./PlatformProblemMapping'),
  UserPlatformSyncState: require('./UserPlatformSyncState'),
  UserTopicStats: require('./UserTopicStats'),
  UserSubmission: require('./UserSubmission'),
  UserContest: require('./UserContest'),
  SyncLog: require('./SyncLog'),
  IntegrationMetadata: require('./IntegrationMetadata'),
};
