const mongoose = require('mongoose');

/**
 * UserRecommendationLog Schema - Recommendation audit trail
 * Tracks all recommendations given to user and their acceptance/outcomes
 * Used for: Recommendation quality evaluation, feedback loops, personalization
 * 
 * Design: Immutable log, one entry per recommendation decision
 * Used by: RecommendationEngine, FeedbackAnalyzer, PersonalizationService
 */
const userRecommendationLogSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    topicId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Topic',
      index: true,
    },

    topicName: String,

    // Recommendation type
    recommendationType: {
      type: String,
      enum: [
        'practice_problem',
        'topic_revision',
        'difficulty_increase',
        'difficulty_decrease',
        'mock_interview',
        'learning_resource',
        'targeted_weakness_fix',
        'retention_reinforcement',
      ],
      required: true,
      index: true,
    },

    // Recommended action
    recommendedAction: {
      type: String,
      required: true,
      description: 'Description of what was recommended',
    },

    // Recommendation reasoning
    reasonCode: {
      type: String,
      enum: [
        'low_mastery_score',
        'high_mistake_rate',
        'retention_decay',
        'insufficient_practice',
        'consistent_difficulty_struggle',
        'careless_mistakes',
        'time_management_issues',
        'readiness_gap',
        'weakness_signal',
        'spaced_repetition_schedule',
      ],
      required: true,
      index: true,
    },

    reasonDescription: String,

    // Recommendation metadata
    problemIds: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Problem',
      },
    ],

    difficulty: {
      type: String,
      enum: ['easy', 'medium', 'hard'],
    },

    estimatedDurationMinutes: Number,

    // Confidence in recommendation
    confidenceScore: {
      type: Number,
      min: 0,
      max: 100,
    },

    // Generated by which system
    generatedBy: {
      type: String,
      enum: [
        'mastery_engine',
        'weakness_detector',
        'retention_model',
        'readiness_scorer',
        'practice_recommender',
        'mock_interview_suggester',
        'manual_admin',
      ],
      required: true,
    },

    // Recommendation timing
    generatedAt: {
      type: Date,
      default: Date.now,
      immutable: true,
      index: true,
    },

    expiresAt: {
      type: Date,
      description: 'When this recommendation becomes stale',
      index: true,
    },

    // User feedback
    status: {
      type: String,
      enum: ['pending', 'accepted', 'declined', 'expired', 'archived'],
      default: 'pending',
      index: true,
    },

    acceptedAt: Date,

    userFeedback: {
      rating: {
        type: Number,
        min: 1,
        max: 5,
      },
      comment: String,
      helpful: Boolean,
    },

    // Outcome tracking
    outcome: {
      type: String,
      enum: ['positive', 'neutral', 'negative', 'not_acted_upon'],
    },

    outcomeMetrics: {
      problemsCompleted: Number,
      problemsSolved: Number,
      timeSpent: Number, // minutes
      masteryImprovement: Number,
      difficultyProgression: Boolean,
    },

    // For chaining recommendations
    parentRecommendationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'UserRecommendationLog',
    },

    childRecommendations: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'UserRecommendationLog',
      },
    ],

    // Context snapshot (for historical analysis)
    contextSnapshot: {
      masteryScore: Number,
      readinessScore: Number,
      riskLevel: String,
      daysId: Number,
    },

    // A/B testing
    experimentGroup: String,
    variant: String,

    // Platform source
    platform: {
      type: String,
      enum: ['web', 'mobile', 'api'],
    },

    _deduplicationKey: {
      type: String,
      unique: true,
      sparse: true,
      index: true,
    },

    updatedAt: {
      type: Date,
      default: Date.now,
      index: true,
    },
  },
  {
    timestamps: true,
    collection: 'user_recommendation_log',
  }
);

// Indexes for efficient querying
userRecommendationLogSchema.index({ userId: 1, generatedAt: -1 });
userRecommendationLogSchema.index({ userId: 1, status: 1 });
userRecommendationLogSchema.index({ userId: 1, topicId: 1 });
userRecommendationLogSchema.index({ generatedBy: 1, outcome: 1 });
userRecommendationLogSchema.index({ expiresAt: 1 }); // For cleanup jobs

// Pre-save hook
userRecommendationLogSchema.pre('save', function(next) {
  if (!this._deduplicationKey && this.userId && this.generatedAt) {
    this._deduplicationKey = `${this.userId}-${this.recommendationType}-${this.generatedAt}`;
  }
  next();
});

module.exports = mongoose.model('UserRecommendationLog', userRecommendationLogSchema);
